Colors = {
	colors:
		[
			"black",
			"blue",
			"red",
			"purple",
			"turquoise",
			"green",
			"orange",
			"magenta",
			"gold",
			"yellow",
			"violet",
			"khaki",
			"maroon",
			"beige",
			"darkorchid",
			"darkblue",
			"darkorange",
			"fuchsia",
			"aqua",
			"darkgrey",
			"darkkhaki",
			"navy",
			"darkolivegreen",
			"darkcyan",
			"darksalmon",
			"lightcyan",
			"lightyellow",
			"lightgreen",
			"lightpink",
			"darkgreen",
			"silver",
			"darkviolet",
			"lightblue",
			"brown",
			"darkmagenta",
			"lime",
			"indigo",
			"azure",
			"lightgrey",
			"olive",
			"pink",
			"cyan",
			"darkred",
		],
	colorMaps :
		{
			aqua: "#00ffff",
			azure: "#f0ffff",
			beige: "#f5f5dc",
			black: "#000000",
			blue: "#0000ff",
			brown: "#a52a2a",
			cyan: "#00ffff",
			darkblue: "#00008b",
			darkcyan: "#008b8b",
			darkgrey: "#a9a9a9",
			darkgreen: "#006400",
			darkkhaki: "#bdb76b",
			darkmagenta: "#8b008b",
			darkolivegreen: "#556b2f",
			darkorange: "#ff8c00",
			darkorchid: "#9932cc",
			darkred: "#8b0000",
			darksalmon: "#e9967a",
			darkviolet: "#9400d3",
			fuchsia: "#ff00ff",
			gold: "#ffd700",
			green: "#008000",
			indigo: "#4b0082",
			khaki: "#f0e68c",
			lightblue: "#add8e6",
			lightcyan: "#e0ffff",
			lightgreen: "#90ee90",
			lightgrey: "#d3d3d3",
			lightpink: "#ffb6c1",
			lightyellow: "#ffffe0",
			lime: "#00ff00",
			magenta: "#ff00ff",
			maroon: "#800000",
			navy: "#000080",
			olive: "#808000",
			orange: "#ffa500",
			pink: "#ffc0cb",
			purple: "#800080",
			violet: "#800080",
			red: "#ff0000",
			silver: "#c0c0c0",
			turquoise: "#40e0d0",
			white: "#ffffff",
			yellow: "#ffff00"
		},
	nameMaps :
		{
			aqua: "Aqua",
			azure: "Azure",
			beige: "Beige",
			black: "Black",
			blue: "Blue",
			brown: "Brown",
			cyan: "Cyan",
			darkblue: "Dark Blue",
			darkcyan: "Dark Cyan",
			darkgrey: "Dark Grey",
			darkgreen: "Dark Green",
			darkkhaki: "Dark Khaki",
			darkmagenta: "Dark Magenta",
			darkolivegreen: "Dark Olive Green",
			darkorange: "Dark Orange",
			darkorchid: "Dark Orchid",
			darkred: "Dark Red",
			darksalmon: "Dark Salmon",
			darkviolet: "Dark Violet",
			fuchsia: "Fuchsia",
			gold: "Gold",
			green: "Green",
			indigo: "Indigo",
			khaki: "Khaki",
			lightblue: "Light Blue",
			lightcyan: "Light Cyan",
			lightgreen: "Light Green",
			lightgrey: "Light Grey",
			lightpink: "Light Pink",
			lightyellow: "Light Yellow",
			lime: "Lime",
			magenta: "Magenta",
			maroon: "Maroon",
			navy: "Navy",
			olive: "Olive",
			orange: "Orange",
			pink: "Pink",
			purple: "Purple",
			violet: "Violet",
			red: "Red",
			silver: "Silver",
			turquoise: "Turquoise",
			white: "White",
			yellow: "Yellow",
		},
	colorTracker: -1,
};
